CLJ ?= clj

all: dev

dev:
	$(CLJ) -M:dev dev

logs:
	$(CLJ) -M:dev logs

deploy:
	$(CLJ) -M:dev deploy

prod-dev:
	$(CLJ) -M:dev prod-dev

uberjar:
	$(CLJ) -M:dev uberjar


.PHONY: all dev logs deploy prod-dev uberjar
