#!/usr/bin/env bb

(require '[pod.babashka.postgresql :as pg])

(def db {:dbtype   "postgresql"
         :host     "localhost"
         :dbname   "mytest"
         :user     "test"
         :password "test"
         :port     5432})

(let [version (pg/execute! db ["SELECT version()"])]
  version)

(pg/execute! db ["SELECT gen_random_uuid()"])

(pg/execute! db ["SELECT '안녕?'"])

(pg/execute! db ["show server_encoding;"])
(pg/execute! db ["show client_encoding;"])

(pg/execute! db ["CREATE TABLE IF NOT EXISTS employee (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(128),
age INTEGER,
created TIMESTAMP)"])

(let [name "Steve"
      age 24]
  (pg/execute! db ["INSERT INTO employee (name, age, created) VALUES (?, ?, now())" name age]))

(let [employees (pg/execute! db ["SELECT * FROM employee"])]
  (doseq [employee employees]
    (prn :employee employee)))

(pg/execute! db ["DELETE FROM employee"])
