# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'GoogleMapsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for GoogleMapsExample

  target 'GoogleMapsExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleMapsExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
