CLJ ?= clj

all: sample1

sample1:
	$(CLJ) -X:sample1

sample2:
	$(CLJ) -X:sample2

sample3:
	$(CLJ) -X:sample3

sample4:
	$(CLJ) -X:sample4

sample5:
	$(CLJ) -X:sample5

test:
	$(CLJ) -T:build test

clean:
	rm -rf target

.PHONY: all sample1 sample2 sample3 sample4 sample5 test clean
