######################################################################
# Automatically generated by qmake (2.01a) ? 1? 3 14:15:29 2019
######################################################################

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
