######################################################################
# Automatically generated by qmake (2.01a) ? 1? 3 14:15:29 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
